version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    container_name: todo
    networks:
      - main
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "9229:9229"

networks:
  main:
    external: true
